### ISSUE TITLE
multiple connection instance

### ISSUE THREAD

**Issue by migomhmi** [smurfpandey/mysqlweb#21]
One might like to have connection to multiple host at a time

**Comment by smurfpandey** [comment]
I have thought about it. 
For now there is a workaround, you can run multiple instances of mysqlweb listening on different HTTP port using CLI options.

Check https://github.com/sosedoff/pgweb/wiki/Usage for more detail

**Comment by smurfpandey** [comment]
@migomhmi I have a solution for this, using way you can have multiple open connections to different hosts, but you will need to open them in different browsers ;)

**Comment by smurfpandey** [comment]
@migomhmi I have a solution as WIP. Hopefully by this weekend it will be ready. :)
